name: Deploy Microservice

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '18.x'
            - name: Install dependencies
              run: npm ci
            - name: Run Linting
              run: npm run lint
            - name: Run tests
              run: npm test
            - name: Build
              run: npm run build
            - name: Run contract tests
              run: npm run test:contracts
            - name: Build and push Docker image
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: true
                  tags: ${{ secrets.REGISTRY }}/${{ github.repository }}:${{ github.sha }}
            - name: Deploy to Kubernetes
              uses: actions-hub/kubectl@master
              env:
                  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
              with:
                  args: set image deployment/${{ github.event.repository.name }} ${{ github.event.repository.name }}=${{ secrets.REGISTRY }}/${{ github.repository }}:${{ github.sha }}
            - name: Verify deployment
              uses: actions-hub/kubectl@master
              env:
                  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
              with:
                  args: rollout status deployment/${{ github.event.repository.name }}
